
GET http://localhost:3000/students

###
GET http://localhost:3000/students/636e6eead6ebf3b5e07e4654


###
POST http://localhost:3000/students
Content-Type: application/json

{
    "email":"bella@gmail.com",
    "first_name":"bella",
    "last_name":"tete"
      
}

###
PATCH  http://localhost:3000/students/636e7c9fa9a8844cca37e095
Content-Type: application/json

{
    "email":"chado1@miu.edu",
    "first_name":"chado1",
    "last_name":"Tata"

}
###
DELETE http://localhost:3000/students/636e707ec291a1f4152460ea


###
POST http://localhost:3000/users/signup
Content-Type: application/json

{
    "email":"user2@miu.edu",
    "fullname":"user2",
    "password":"12345",
    "avatar":"https://image.shutterstock.com/image-vector/user-sign-icon-person-symbol-260nw-229318795.jpg"

}
###
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email":"user2@miu.edu",
    "password":"12345"
   

}